const accounts = [
  {
    mediaCode: "fb",
    media: "facebook",
    userName: "@rceballos",
    follower_count: 1897,
    follow: "FOLLOWERS",
    user_dayCount: 25,
    classes: "wrapper fbColor",
    mediaActivity: "Page view",
    dayActivityCount: 83,
    mediaGrowth: "1%",
    mediaActivity2: "Likes",
    dayActivityCount2: 500,
    mediaGrowth2: "20%",
  },
  {
    mediaCode: "tw",
    media: "twitter",
    userName: "@tw_rceballos",
    follower_count: 1597,
    follow: "FOLLOWERS",
    user_dayCount: 15,
    classes: "wrapper twColor",
    mediaActivity: "Retweets",
    dayActivityCount: 54,
    mediaGrowth: "113%",
    mediaActivity2: "Likes",
    dayActivityCount2: 200,
    mediaGrowth2: "10%",
  },
  {
    mediaCode: "ig",
    media: "instagram",
    userName: "@ig_rceballos",
    follower_count: 1897,
    follow: "FOLLOWERS",
    user_dayCount: "-25",
    classes: "wrapper igColor",
    mediaActivity: "Profile view",
    dayActivityCount: 24,
    mediaGrowth: "2%",
    mediaActivity2: "Likes",
    dayActivityCount2: 677,
    mediaGrowth2: "12%",
  },
  {
    mediaCode: "yt",
    media: "youtube",
    userName: "yt_rceballos",
    follower_count: 1197,
    follow: "SUBSCRIBERS",
    user_dayCount: 65,
    classes: "wrapper ytColor",
    mediaActivity: "Total view",
    dayActivityCount: 45,
    mediaGrowth: "7%",
    mediaActivity2: "Likes",
    dayActivityCount2: 1245,
    mediaGrowth2: "20%",
  },
];

export default accounts;
